#include "nsISupports.idl"

[scriptable, uuid (3ff257c4-c26f-4ee2-8b49-9fba266e6cde)]
interface arIAkahukuURIParam : nsISupports {
  attribute AString type;
  attribute AString hash;
  
  attribute AString protocol;
  attribute AString host;
  attribute AString path;
  
  attribute AString original;
};

[scriptable, uuid (65e9b537-0fa4-4e73-ac9c-77a75fdf2c9f)]
interface arIAkahukuProtocolHandler : nsISupports {
  AString enAkahukuURI (in AString type, in AString uri);
  
  PRBool isAkahukuURI (in AString uri);
  AString deAkahukuURI (in AString uri);
  arIAkahukuURIParam getAkahukuURIParam (in AString uri);
};
